name: Release

on: workflow_dispatch

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gettext

    - name: Build plasmoid package
      run: python3 ./kpac build

    - name: Get latest tag
      id: tag
      run: |
        git fetch --tags
        LATEST_TAG=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | head -n 1)
        echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Get package name
      id: package
      run: |
        PACKAGE_NAME=$(ls *.plasmoid | head -1)
        echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.package.outputs.name }}
        tag_name: ${{ steps.tag.outputs.latest_tag }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}